// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace PcBuilderModelAI_WebApi_ValuePrediction
{
    public partial class PcBuilderModelAI
    {
        /// <summary>
        /// model input class for PcBuilderModelAI.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"total_price_usd")]
            public float Total_price_usd { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"cpu_compute_score")]
            public float Cpu_compute_score { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"cpu_multicore_score")]
            public float Cpu_multicore_score { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"cpu_efficiency_score")]
            public float Cpu_efficiency_score { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"gpu_compute_score")]
            public float Gpu_compute_score { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"gpu_power_efficiency")]
            public float Gpu_power_efficiency { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"ram_capacity_score")]
            public float Ram_capacity_score { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"ram_bandwidth_score")]
            public float Ram_bandwidth_score { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"has_gpu")]
            public float Has_gpu { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"computer_type")]
            public string Computer_type { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"performance_per_dollar")]
            public float Performance_per_dollar { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PcBuilderModelAI.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"total_price_usd")]
            public float Total_price_usd { get; set; }

            [ColumnName(@"cpu_compute_score")]
            public float Cpu_compute_score { get; set; }

            [ColumnName(@"cpu_multicore_score")]
            public float Cpu_multicore_score { get; set; }

            [ColumnName(@"cpu_efficiency_score")]
            public float Cpu_efficiency_score { get; set; }

            [ColumnName(@"gpu_compute_score")]
            public float Gpu_compute_score { get; set; }

            [ColumnName(@"gpu_power_efficiency")]
            public float Gpu_power_efficiency { get; set; }

            [ColumnName(@"ram_capacity_score")]
            public float Ram_capacity_score { get; set; }

            [ColumnName(@"ram_bandwidth_score")]
            public float Ram_bandwidth_score { get; set; }

            [ColumnName(@"has_gpu")]
            public float Has_gpu { get; set; }

            [ColumnName(@"computer_type")]
            public float[] Computer_type { get; set; }

            [ColumnName(@"performance_per_dollar")]
            public float Performance_per_dollar { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PcBuilderModelAI.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
